import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Icons } from "@/components/icons";
import { Toaster } from "@/components/ui/sonner";
import { ProgressBar } from "@/components/progress-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProgressBar className="fixed top-0 z-[100] h-1 bg-primary">
          {children}
        </ProgressBar>
        <Toaster
          closeButton
          icons={{
            success: (
              <Icons.circleDashedCheck className="size-5 text-[#089445] dark:text-[#32d46c]" />
            ),
            info: <Icons.infoCircle className="size-5 text-[#3498d9]" />,
            warning: <Icons.alertTriangle className="size-5 text-[#f0c100]" />,
            error: (
              <Icons.exclamationCircle className="size-5 text-[#da1415]" />
            ),
          }}
        />
      </body>
    </html>
  );
}
